# -*- coding: utf-8 -*-
"""Arayuz metinleri Turkce -> Ingilizce (platform.js icindeki tt('...') anahtarlari).

{0} {1} ... yer tutucudur. Deger {"1": tekil, "*": cogul} olabilir (ilk arguman 1 ise tekil).
Deepin platform ekraninin kendi Ingilizce metinleri korundu: "Monitor closely", "Sorted from high to low",
"AI can make mistakes. Please verify the answers.", "Go Back" yerine "Back".
"""

def _p(one, many):
    return {"1": one, "*": many}


TXT = {
    " ve ": " and ",
    "+{0} ağ daha": _p("+{0} more network", "+{0} more networks"),
    "+{0} uyarı daha": _p("+{0} more alert", "+{0} more alerts"),
    "+{0} varlık daha, Uyarılar sekmesinde": _p("+{0} more entity, in the Alerts tab", "+{0} more entities, in the Alerts tab"),
    "<b>{0}</b> incelemesini açtım.": "I opened the <b>{0}</b> investigation.",
    "{0} kaynak": _p("{0} source", "{0} sources"),
    "Şunları sorabilirsiniz:": "You can ask:",
    "Adımlar": "Steps",
    "Adımlar bölümünden": "From the Steps section",
    "Akış": "Flows",
    "Ana menü": "Main menu",
    "Ana sayfa": "Home",
    "Asistan": "Assistant",
    "Ayrıntı": "Details",
    "Ayrıntıyı aç": "Expand details",
    "Ayrıntıyı kapat": "Collapse details",
    "Ağ bölgesi": "Network zones",
    "Ağ geçişleri": "Network flows",
    "Ağ sayısı": "Networks",
    "Ağ tanımı": "Network name",
    "Aşama": "Stage",
    "Bağlam": "Context",
    "Başka açıklamayı düşündüren": "Pointing to another explanation",
    "Benzer görevdekilerden giden": "Peers going there",
    "Bilgisayar": "Computer",
    "Bir ağa tıklayın, ayrıntısı burada görünür.": "Click a network to see its details here.",
    "Bir incelemeyi ya da varlık adını yazabilirsiniz.": "You can type an investigation or an entity name.",
    "Bir kullanıcının yedi günü: hangi kayıt kaynağında ne yaptı": "A user's seven days: what they did in each log source",
    "Bir saldırıyı düşündüren": "Pointing to an attack",
    "Bir tekniğe tıklayın: o tekniğe düşen uyarılar altta listelenir. İki teknik seçerseniz ortak varlıkları görürsünüz.": "Click a technique: the alerts that fall under it are listed below. Select two techniques to see their shared entities.",
    "Birim": "Unit",
    "Bu bir saldırı mı?": "Is this an attack?",
    "Bu dönemde inceleme yok.": "There are no investigations in this period.",
    "Bu dönemde kayıt yok": "No records in this period",
    "Bu inceleme bir saldırı tekniğiyle eşlenmiyor; operasyonel bir bulgudur.": "This investigation does not map to an attack technique; it is an operational finding.",
    "Bu inceleme {0} tekniğin izine düşüyor:": _p("This investigation matches the trace of {0} technique:", "This investigation matches the traces of {0} techniques:"),
    "Bu incelemenin ham kayıt satırları <b>Kanıt</b> sekmesinde. {0} satırdan {1} tanesi ekranda, tamamı {2} dosyasında.": "The raw log lines of this investigation are in the <b>Evidence</b> tab. {1} of the {0} lines are on screen; all of them are in the {2} file.",
    "Bu incelemeyi oluşturan {0} uyarı. Her uyarı tek bir kayıt kaynağından ve tek bir davranıştan gelir; inceleme, bunları aynı hikâyede toplar.": _p("{0} alert makes up this investigation. Each alert comes from a single log source and a single behavior; the investigation gathers them into one story.", "{0} alerts make up this investigation. Each alert comes from a single log source and a single behavior; the investigation gathers them into one story."),
    "Bu incelemeyi sonuçlandırmak için eksik olan {0} bilgi. Bilgi geldiğinde inceleme yeniden değerlendirilir.": _p("{0} piece of information is missing to conclude this investigation. Once it arrives, the investigation is re-evaluated.", "{0} pieces of information are missing to conclude this investigation. Once they arrive, the investigation is re-evaluated."),
    "Bu seçimde inceleme yok": "No investigations in this selection",
    "Bu soruya cevap verecek bir alan kayıtlarda yok.": "No field in the records answers this question.",
    "Bugün": "Today",
    "Bugün dikkat isteyen <b>{0} inceleme</b> var. Toplam {1} inceleme arasından {2} tanesi yüksek öncelikli.": _p("<b>{0} investigation</b> needs attention today. {2} of the {1} investigations is high priority.", "<b>{0} investigations</b> need attention today. {2} of the {1} investigations are high priority."),
    "Bugün ne var?": "What's new today?",
    "Bölge çifti": "Zone pairs",
    "Bölgeler arası bağlantılar, hangi güvenlik cihazından geçtikleri": "Connections between zones and the security devices they pass through",
    "Cevabı kimde": "Who has the answer",
    "Deepin Security size nasıl yardımcı olabilir?": "How can Deepin Security help you?",
    "Denedi, engellendi": "Tried, blocked",
    "Dil": "Language",
    "Diğer engellenen ağlar": "Other blocked networks",
    "Dosya": "File",
    "Durum": "Status",
    "Dönem seçimini kaldır": "Clear the period selection",
    "Dönemi ya da öncelik sekmesini değiştirin.": "Change the period or the priority tab.",
    "Düşük": "Low",
    "Dış adres bloğu": "External address block",
    "Dışarıdan kuruma ulaşan istek": "Requests reaching the organization from outside",
    "Eksik bilgi": "Missing information",
    "Eksik bilgiyi göster": "Show missing information",
    "En önemli inceleme": "Top investigation",
    "En önemli inceleme <b>{0}</b>.": "The top investigation is <b>{0}</b>.",
    "Engellendi": "Blocked",
    "Engellendi; grubun başka üyeleri de aynı ağı deniyor": "Blocked; other members of the group try the same network too",
    "Engellendi; hiçbir istek geçmedi": "Blocked; no request got through",
    "Engellenen": "Blocked",
    "Engellenen ağ, toplam": "Blocked networks, total",
    "Eşleşen uyarı yok": "No matching alerts",
    "Eşleşen varlık yok": "No matching entities",
    "Genel bakış": "Overview",
    "Geri": "Back",
    "Geçen istek": "Allowed requests",
    "Graf": "Graph",
    "Grafı aç": "Open graph",
    "Grubun da engellendiği": "Also blocked for the group",
    "Grubun da engellendiği ağ": "Networks also blocked for the group",
    "Grubun da engellendiği ağlar": "Networks also blocked for the group",
    "Grubun da gittiği": "Also visited by the group",
    "Grubun da gittiği ağ": "Networks the group also visits",
    "Grubun yolu": "Group's path",
    "Gönder": "Send",
    "Gün": "Day",
    "Gün gün": "Day by day",
    "Güncel Uyarılar": "Current Alerts",
    "Günlük özet": "Daily briefing",
    "Ham kayıt": "Raw log",
    "Ham kayıt paketinden": "From the raw log package",
    "Ham kayıt satırları": "Raw log lines",
    "Ham kayıtlar nerede?": "Where are the raw logs?",
    "Hemen bakın": "Needs attention now",
    "Henüz sabitlenen inceleme yok. İnceleme dosyasında Sabitle düğmesini kullanın.": "No pinned investigations yet. Use the Pin button in the investigation file.",
    "Her iki teknik de aynı aşamada.": "Both techniques are in the same stage.",
    "Kanıt": "Evidence",
    "Kanıt ve eksik bilgi bölümlerinden": "From the Evidence and Missing information sections",
    "Kanıtı göster": "Show evidence",
    "Kapat": "Close",
    "Kaydeden cihaz": "Logging device",
    "Kaynak": "Source",
    "Kayıt aralığı": "Log period",
    "Kayıt bunu tek başına söyleyemez. Bu inceleme için belirleyici bilgi eksik bilgi listesinde.": "The logs alone cannot tell this. The deciding information for this investigation is in the missing information list.",
    "Kayıt bunu tek başına söyleyemez. Görülen davranış bir tekniğin izi olabilir, başka açıklamaları da olabilir.": "The logs alone cannot tell this. The observed behavior could be the trace of a technique, but it may have other explanations.",
    "Kayıt kaynakları": "Log sources",
    "Kayıt kaynağı": "Log source",
    "Kayıtlar kurum dışına çıkmaz. Bağlam dosyaları uyarıdaki her adres ve hesabın kim ya da ne olduğunu bulmak için kullanılır.": "Logs never leave the organization. Context files are used to find out who or what each address and account in an alert is.",
    "Kayıtlarda olmayan": "Missing from the records",
    "Kayıtlardaki olayların sırası:": "Order of the events in the logs:",
    "Kim ya da ne etkileniyor?": "Who or what is affected?",
    "Kime": "To whom",
    "Kimlere sorulur?": "Who should be asked?",
    "Kişi": "Person",
    "Kişi sorgusu": "User lookup",
    "Konu": "Topic",
    "Kullanıcı": "User",
    "Kullanıcı adı yazın, örn. {0}": "Type a username, e.g. {0}",
    "Kullanıcı ara": "Search users",
    "Kurgusal kurumla hazırlanmış demo verisi. Dönem: {0}, son güncelleme {1}.": "Demo data prepared with a fictional organization. Period: {0}, last updated {1}.",
    "Kurum içi geçişler (doğu-batı)": "Internal flows (east-west)",
    "Kurum sınırını geçen (kuzey-güney)": "Crossing the organization boundary (north-south)",
    "MITRE eşlemesi": "MITRE mapping",
    "MITRE sayfasını aç": "Open the MITRE page",
    "Matris": "Matrix",
    "Matris toplamı: {0} istek, Akış sekmesindeki reddedilen toplamıyla aynıdır.": "Matrix total: {0} requests, the same as the denied total in the Flows tab.",
    "Matris toplamı: {0} istek, Akış sekmesindeki ulaşan toplamıyla aynıdır.": "Matrix total: {0} requests, the same as the reached total in the Flows tab.",
    "Ne değişti?": "What changed?",
    "Ne oldu": "What happened",
    "Neler eksik?": "What's missing?",
    "Nereden": "From",
    "Nereye": "To",
    "O gün ilk kez": "First seen that day",
    "Okunan kayıtlar ve bunları anlamlandıran bağlam dosyaları": "The logs that are read and the context files that make sense of them",
    "Orta": "Medium",
    "Oturum": "Sessions",
    "Paneli yeniden boyutlandır": "Resize the panel",
    "Reddedilen": "Denied",
    "Reddedilen istek": "Denied requests",
    "Rutin takip": "Routine follow-up",
    "Sabitle": "Pin",
    "Sabitleme kaldırıldı": "Pin removed",
    "Sabitlendi": "Pinned",
    "Sabitlenenler": "Pinned",
    "Satır kaynak bölge, sütun hedef bölge. Renk logaritmik ölçekte.": "Rows are source zones, columns are target zones. Color is on a logarithmic scale.",
    "Servis": "Service",
    "Seçili teknikte bu dönemde uyarı yok": "No alerts for the selected technique in this period",
    "Sistem": "System",
    "Son 3 gün": "Last 3 days",
    "Son uyarıya göre": "Latest alert",
    "Soru": "Question",
    "Sürükleyerek boyutlandırın": "Drag to resize",
    "Sıralama": "Sort",
    "Sıralama:": "Sort:",
    "Takip ettiğiniz kayıt kaynaklarındaki son değişiklikler": "Latest changes in the log sources you follow",
    "Toplam": "Total",
    "Tüm dönem": "Entire period",
    "Tüm incelemeler": "All investigations",
    "Tüm kaynaklar": "All sources",
    "Tüm uyarılar": "All alerts",
    "Tüm öncelikler": "All priorities",
    "Tümü": "All",
    "Tür": "Type",
    "Ulaşan": "Reached",
    "Ulaşıldı; grubun başka üyeleri de gidiyor": "Reached; other members of the group go there too",
    "Ulaşıldı; yalnız bu kişi gidiyor": "Reached; only this person goes there",
    "Uyarı": "Alerts",
    "Uyarı sayısına göre": "Alert count",
    "Uyarı türü": "Alert type",
    "Uyarılar": "Alerts",
    "Uyarılarda ara": "Search alerts",
    "Uyarıları göster": "Show alerts",
    "Uyarıların günlere dağılımı ve kayıtlardaki olayların sırası.": "Alerts per day and the order of events in the logs.",
    "Uyarıların teknik etiketlerinden": "From the alerts' technique tags",
    "VPN istek": "VPN requests",
    "Varlık": "Entity",
    "Varlık adına göre": "Entity name",
    "Varlık ara": "Search entities",
    "Varlık, tür veya açıklama ara": "Search by entity, type or description",
    "Varlıklar": "Entities",
    "Veri kaynakları": "Data sources",
    "Yakından izleyin": "Monitor closely",
    "Yalnız bu kişi": "Only this person",
    "Yalnız bu kişinin denediği": "Tried only by this person",
    "Yalnız bu kişinin ulaştığı": "Reached only by this person",
    "Yalnız bu kişinin ulaştığı ağ": "Networks reached only by this person",
    "Yapay zekâ hata yapabilir. Lütfen cevapları doğrulayın.": "AI can make mistakes. Please verify the answers.",
    "Yardımcı paneller": "Side panels",
    "Yeniden eskiye": "Newest first",
    "Yönetici yetkisi": "Admin privileges",
    "Yüksek": "High",
    "Yüksekten düşüğe sıralı": "Sorted from high to low",
    "Zaman": "Timeline",
    "Zaman sekmesinden": "From the Timeline tab",
    "Zamanı göster": "Show timeline",
    "aşama": "stages",
    "aşama:": "stage:",
    "benzer görevdekiler": "similar roles",
    "bugün": "today",
    "cevabı:": "who answers:",
    "engellendi, tabloda": "blocked, see table",
    "hiçbiri": "none",
    "inceleme": "investigations",
    "izlenen teknik": "monitored techniques",
    "için ortak varlık yok.": "have no shared entities.",
    "için ortak varlıklar:": "share these entities:",
    "kaynak": "sources",
    "kayıtlarda tanımlı değil": "not defined in the records",
    "kişi": "people",
    "teknik etiketli uyarı": "alerts with a technique tag",
    "teknikte uyarı var": "techniques with alerts",
    "uyarı": "alerts",
    "yüksek": "high",
    "{0} ({1} / {2})": "{0} ({1} / {2})",
    "{0} / {1} satır gösteriliyor": "Showing {0} of {1} lines",
    "{0} / {1} uyarı": "{0} / {1} alerts",
    "{0} ağ": _p("{0} network", "{0} networks"),
    "{0} bölge çifti": _p("{0} zone pair", "{0} zone pairs"),
    "{0} dönemi kayıtlarından": "From the logs of {0}",
    "{0} eksik bilgi": _p("{0} missing item", "{0} missing items"),
    "{0} inceleme": _p("{0} investigation", "{0} investigations"),
    "{0} inceleme buldum:": _p("I found {0} investigation:", "I found {0} investigations:"),
    "{0} incelemesini aç": "Open the {0} investigation",
    "{0} istek": _p("{0} request", "{0} requests"),
    "{0} için ağ rotaları": "Network routes for {0}",
    "{0} uyarı": _p("{0} alert", "{0} alerts"),
    "{0} uyarının kaydından": _p("From the record of {0} alert", "From the records of {0} alerts"),
    "{0} varlığın kaydından": _p("From the record of {0} entity", "From the records of {0} entities"),
    "{0} yüksek öncelikli inceleme var:": _p("There is {0} high-priority investigation:", "There are {0} high-priority investigations:"),
    "{0} öncelik": "{0} priority",
    "Çizgi kalınlığı istek sayısını gösterir (logaritmik ölçek). Gri çizgi, benzer görevdekilerin o ağa gönderdiği isteği temsil eder.": "Line thickness shows the number of requests (logarithmic scale). The gray line represents the requests peers sent to that network.",
    "Çözünürlük gündür. Dönemin ilk günü taban sayılır, o günün ilk görülenleri listelenmez.": "Resolution is one day. The first day of the period is the baseline, so what is first seen on that day is not listed.",
    "Öncelik": "Priority",
    "Öncelik sırasına göre": "In priority order",
    "Önceliğe göre": "Priority",
    "Önem": "Severity",
    "Önem sırasına göre": "By severity",
    "Özetle": "Summarize",
    "İK durumu:": "HR status:",
    "İki teknik farklı aşamalarda ({0}, {1}); aynı varlıkta ardışık aşamalar görülüyor.": "The two techniques are in different stages ({0}, {1}); consecutive stages are seen on the same entity.",
    "İlk görülme": "First seen",
    "İnceleme": "Investigation",
    "İnceleme dosyasında listelenir": "Listed in the investigation file",
    "İnceleme sabitlendi": "Investigation pinned",
    "İnceleme ve varlık adlarında arandı": "Searched in investigation and entity names",
    "İncelemeyi aç": "Open investigation",
    "İstek": "Requests",
    "İzlenen teknikler ve bu dönemde uyarı üretenler": "Monitored techniques and those that raised alerts in this period",
    "Şu sorular bu incelemenin kayıtlarından cevaplanabilir:": "These questions can be answered from this investigation's records:",
}
