# -*- coding: utf-8 -*-
"""Veri katmani Turkce -> Ingilizce sozlugu (sablon anahtarli; bkz. cevir.py).

Yer tutucular: {N} sayi, {P} yuzde, {D} tarih, {T} saat, {K} degismeyen kimlik (adres, makine, kisi adi).
Sira degisiyorsa {N1} {N2} ... (kaynaktaki sirasi). Deger {"1": tekil, "*": cogul} olabilir (ilk sayi 1 ise tekil).
Terimler: inceleme = investigation, uyari = alert, varlik = entity.
"""

def _p(one, many):
    return {"1": one, "*": many}


SOZLUK = {
    "": "",
    "Adres artık yok ({N}) ama hâlâ çağrılıyor: {N} istek": "Address no longer exists ({N1}) but is still being called: {N2} requests",
    "Adres bloklarının kime ait olduğu ve yetkili test kaydı": "Who owns the address blocks, and the authorized test record",
    "Adres bloğunun kime ait olduğu": "Who owns the address block",
    "Aktif çalışıyor": "Actively employed",
    "Alan hesapları": "Domain accounts",
    "Alarm üretilmemiş": "No alarm was raised",
    "Altyapı ve Sistem Yönetimi": "Infrastructure and Systems Management",
    "Altyapı İzleme": "Infrastructure Monitoring",
    "Anlamı": "Meaning",
    "Aracın kullanım amacı": "Purpose of the tool",
    "Arandı, bulunamadı": "Searched, not found",
    "Araç aktarımı": "Ingress tool transfer",
    "Arşiv indirildi ve tespit edildi": "Archive downloaded and detected",
    "Aynı ağa reddedilen istekler": "Requests to the same network denied",
    "Aynı ağa tekrarlayan ret": "Repeated denials to the same network",
    "Aynı ağlarda ikinci gece": "Second night on the same networks",
    "Aynı birimde {N} kişi": _p("{N} person in the same unit", "{N} people in the same unit"),
    "Aynı birimden {N} kişi benzer davranış gösteriyor": "{N} people from the same unit show similar behavior",
    "Aynı gün yoğunlaşma": "Concentrated on the same day",
    "Aynı gün {N} yeni iç ağa ulaştı": "Reached {N} new internal networks the same day",
    "Aynı gün {N} yeni iç ağa ulaştı: felaket merkezi ve tanımsız yönetim bloğu": "Reached {N} new internal networks the same day: the disaster recovery site and an undefined management block",
    "Aynı hedeflere yoğunlaşma": "Concentrated on the same targets",
    "Aynı saatlerde bilgisayarda çalışan süreç kaydı": "Record of processes running on the computer at the same hours",
    "Ayrılan personel hesabı": "Departed employee account",
    "Ayrılan {N} hesabın {N}'inde": "In {N2} of {N1} departed accounts",
    "Ayrılmış personelin hesabı etkin, dönemde {N} oturum açılmış": "A departed employee's account is active; {N} sessions were opened in the period",
    "Ayrılmış personelin hesabıyla oturum": "Sessions with a departed employee's account",
    "Ayrılış kaydı {D}, hesap etkin; dönemde {N} gece VPN oturumu açılmış ve {N} ödeme ve kart ağına ulaşılmış.": "Departure recorded on {D}, account still active; VPN sessions were opened on {N1} nights in the period and {N2} payment and card networks were reached.",
    "Ayrılış sonrası hesap etkin": "Account active after departure",
    "Ayrılış sonrası hesap kapatma iş kaydı": "Account closure ticket after departure",
    "Ayrılış sonrası hesap kapatma kaydı": "Account closure record after departure",
    "Açık": "Open",
    "Ağ": "Network",
    "Ağ cihazları envanteri": "Network device inventory",
    "Ağ ekibi": "Network team",
    "Ağ erişim talebi": "Network access request",
    "Ağ parçaları ve bağlantıları": "Network segments and their connections",
    "Ağ paylaşımı keşfi": "Network share discovery",
    "Ağ servisi keşfi": "Network service discovery",
    "Ağ tanımı": "Network name",
    "Ağ taraması": "Network scan",
    "Ağ topolojisi": "Network topology",
    "Ağlar": "Networks",
    "Bakım penceresi kaydı": "Maintenance window record",
    "Baskın kod": "Dominant code",
    "Bağlam": "Context",
    "Bağlı": "Connected",
    "Başka açıklama": "Other explanation",
    "Benzerlerinde olağan {N} ağ": "Typical for peers: {N} networks",
    "Bilgi Güvenliği": "Information Security",
    "Bilgi Güvenliği ekibinin test görevi kaydı": "Information Security team's test assignment record",
    "Bilgisayar için oturum kaydı ve zimmet bilgisi": "Session record and assignment details for the computer",
    "Bilgisayardan ödeme ağına bağlantı": "Connection from the computer to the payment network",
    "Bilgisayarın kullanıcısı": "User of the computer",
    "Bilinen saldırı aracı": "Known attack tool",
    "Bir bilgisayar {N} saatte {N} iç ağa ve {N} farklı porta istek gönderdi; isteklerin {P}'sı reddedildi.": "One computer sent requests to {N2} internal networks and {N3} different ports in {N1} hours; {P} of the requests were denied.",
    "Bir bilgisayarın İndirilenler klasöründe bilinen saldırı aracı arşivi tespit edildi ve engellendi.": "A known attack tool archive was detected in a computer's Downloads folder and blocked.",
    "Birden çok gün": "Multiple days",
    "Birden çok imza sınıfı": "Multiple signature classes",
    "Bloğun sahibi": "Block owner",
    "Bu adreslere istek gönderen uygulamanın kaydı": "Record of the application sending requests to these addresses",
    "Bu dönemde bu {N} bilgisayardan uç nokta kaydı gelmiyor": "No endpoint records arrive from these {N} computers in this period",
    "Bu dönemde uç nokta kaydı yok": "No endpoint records in this period",
    "Bu {N} kişi": "These {N} people",
    "Cevap kodu dağılımı": "Response code distribution",
    "Dakikada bir yoklama": "Polling once a minute",
    "Denetim görevi kaydı": "Audit assignment record",
    "Denetimli test kaydı": "Authorized test record",
    "Değer": "Value",
    "Değişiklik ve bakım kayıtları": "Change and maintenance records",
    "Değişiklik yönetimi": "Change management",
    "Dizin hesabı": "Directory account",
    "Dizin hesapları": "Directory accounts",
    "Dizüstü": "Laptop",
    "Diğer günlerde davranışı olağan": "Behavior is normal on other days",
    "Doğrulanan istasyon {N} katına çıktı": "Authenticating stations rose {N}-fold",
    "Düşük": "Low",
    "Dış tarama": "External scan",
    "Dış uzak servisler": "External remote services",
    "Dış web taraması": "External web scan",
    "En yoğun gün": "Peak day",
    "Engellenen ağ": "Blocked networks",
    "Engellenen ağ, en yüksek": "Blocked networks, highest",
    "Engellenen ağ, ortanca": "Blocked networks, median",
    "Engellenen ağların kayıt durumu": "Record status of the blocked networks",
    "Envanter yöneticisi": "Inventory manager",
    "Erişim beklentisi": "Access expectation",
    "Erişim talebi": "Access request",
    "Erişimin yetki kaydı": "Authorization record for the access",
    "Etki alanı denetleyicisi": "Domain controller",
    "Etkileşimli oturum, yeni bilgisayar": "Interactive session, new computer",
    "Farklı hedef ağ": "Distinct target networks",
    "Farklı port": "Distinct ports",
    "Felaket Merkezi, ödeme sistemleri": "Disaster Recovery Site, payment systems",
    "Finansal Raporlama Uzmanı": "Financial Reporting Specialist",
    "Genel Müdürlük kullanıcı ağı": "Head Office user network",
    "Geçen": "Allowed",
    "Geçerli hesaplar": "Valid accounts",
    "Grubun geri kalanı ({N} kişi)": "Rest of the group ({N} people)",
    "Grup davranışı": "Group behavior",
    "Grup içinde {N} kişilik alt küme: engellenen ağ sayısı grupta olağanın en az {N} katı, ulaşılan yeni ağ yok.": "A subgroup of {N1} people within the group: the number of blocked networks is at least {N2} times the group norm, and no new network was reached.",
    "Grup içinde {N} kişilik alt küme: engellenen ağ sayısı {N} ile {N} arasında, grupta olağan {N}; ulaşılan ağ yok.": "A subgroup of {N1} people within the group: blocked networks range from {N2} to {N3} against a group norm of {N4}; no network was reached.",
    "Grupla kıyas": "Comparison with the group",
    "Grupta olağan": "Group norm",
    "Grupta olağanın en az {N} katı": "At least {N} times the group norm",
    "Grupta olağanın {N} ile {N} katı": "{N1} to {N2} times the group norm",
    "Görev kaydı": "Assignment record",
    "Görülme sıklığı": "Prevalence",
    "Gün": "Day",
    "Günlük dağılım": "Daily breakdown",
    "Güvenlik Operasyonları": "Security Operations",
    "Güvenlik duvarı, yük dengeleyici ve anahtar kayıtları": "Firewall, load balancer and switch records",
    "Güvenlik yönetim ağı": "Security management network",
    "Hafta boyu {N} döndü ({N} istek), alarm üretilmemiş": "Returned {N1} all week ({N2} requests); no alarm was raised",
    "Haftanın her dakikası": "Every minute of the week",
    "Hata oranı arttı": "Error rate increased",
    "Hazine Uygulamaları": "Treasury Applications",
    "Hedef aralıkların envanter ve topolojide karşılığı": "Whether the target ranges appear in the inventory and topology",
    "Hedef ağların envanter kaydı": "Inventory record of the target networks",
    "Hedef ağın durumu": "Status of the target network",
    "Her gün": "Every day",
    "Hesabın bilgisayarından ödeme ağındaki {N} sunucuya bağlantı": "Connections from the account's computer to {N} servers in the payment network",
    "Hesabın kapatılmama nedeni": "Why the account was not closed",
    "Hesap durumu, grup üyelikleri, İK durumu": "Account status, group memberships, HR status",
    "Hesap dönemde ilk kez bir yönetim ağına istek gönderdi; istek engellendi.": "For the first time in the period, the account sent a request to a management network; the request was blocked.",
    "Hesap dönemde ilk kez {N} iç ağa istek gönderdi; {N}'ine ulaşıldı, {N}'sinde istek engellendi.": "For the first time in the period, the account sent requests to {N1} internal networks; {N2} was reached and requests to {N3} were blocked.",
    "Hesap manipülasyonu": "Account manipulation",
    "Hesap {N} gündür aynı iç ağa istek gönderiyor ve her seferinde engelleniyor.": "The account has been sending requests to the same internal network for {N} days and is blocked every time.",
    "Hesap {N} gündür aynı iç ağa istek gönderiyor ve her seferinde engelleniyor; hiçbir istek geçmedi.": "The account has been sending requests to the same internal network for {N} days and is blocked every time; no request got through.",
    "Hesap {N} istasyondan doğruladı": "Account authenticated from {N} stations",
    "Hiçbir istek geçmedi": "No request got through",
    "Kalan {N} kişi için en yoğun gün": "Peak day for the remaining {N} people",
    "Kalıcılık": "Persistence",
    "Kaynak: VPN günlükleri": "Source: VPN logs",
    "Kaynak: etki alanı, güvenlik duvarı": "Source: domain controller, firewall",
    "Kaynak: uç nokta koruması": "Source: endpoint protection",
    "Kaynaklara göre bulgular": "Findings by source",
    "Kendi birimine göre alışılmadık": "Unusual for their own unit",
    "Keşif": "Reconnaissance",
    "Kim olduğu": "Identified by",
    "Kişi, birim ve bağlı olduğu yönetici": "Person, unit and reporting manager",
    "Kişiler": "People",
    "Komuta ve kontrol": "Command and control",
    "Kredi Operasyon Uzmanı": "Credit Operations Specialist",
    "Kredi Operasyonları": "Credit Operations",
    "Kredi Operasyonları yöneticisi": "Credit Operations manager",
    "Kredi Operasyonları, sürekli engellenen istek": "Credit Operations, persistently blocked requests",
    "Kullanıcı": "User",
    "Kullanıcı Ağları": "User Networks",
    "Kullanıcının bu ağa erişmesi gereken bir görev olup olmadığı": "Whether the user has a task that requires access to this network",
    "Kullanıcının rolü ve görev kaydı": "The user's role and assignment record",
    "Kök yola dakikada bir istek, sürekli {N}": "A request to the root path every minute, always {N}",
    "Kıdemli Müşteri Temsilcisi": "Senior Customer Representative",
    "Kıdemli Operasyon Uzmanı": "Senior Operations Specialist",
    "Kısa sürede çok hedef": "Many targets in a short time",
    "Mali İşler": "Finance",
    "Mali İşler, yeni iç ağa gidiş": "Finance, access to a new internal network",
    "Mobil Uygulama Geliştirici": "Mobile Application Developer",
    "Müşteri Temsilcisi": "Customer Representative",
    "Müşteri İletişim Merkezi": "Customer Contact Center",
    "Organizasyon şeması": "Organization chart",
    "Oturum {N} saat {N} dakika sürdü": "The session lasted {N1} hours {N2} minutes",
    "Oturumu açan kişi": "Person who opened the session",
    "SMB ve yönetici paylaşımları": "SMB/Windows admin shares",
    "Servis arızası": "Service outage",
    "Servis kullanılamıyor": "Service unavailable",
    "Servislerin kullanım durumu": "Usage status of the services",
    "Siber Güvenlik Uzmanı": "Cyber Security Specialist",
    "Sistem Yöneticisi": "System Administrator",
    "Sistem Yöneticisi, istasyon sıçraması ve yeni iç ağlar": "System Administrator, station jump and new internal networks",
    "Son parola değişimi": "Last password change",
    "Sonuç": "Result",
    "Sorulmadı": "Not asked",
    "Sunucu hatası ({N}xx)": "Server error ({N}xx)",
    "Sunucu hatası sürüyor": "Server errors continue",
    "Sunucu iç hatası": "Internal server error",
    "Sunucuların adı, adresi, ortamı ve sahibi": "Server name, address, environment and owner",
    "Süre": "Duration",
    "Sürekli engelleme": "Persistent blocking",
    "Sürekli engellenen istek": "Persistently blocked request",
    "Taban günü": "Baseline day",
    "Taban haftası": "Baseline week",
    "Tarama başladı": "Scan started",
    "Tarama özeti": "Scan summary",
    "Test Mühendisi": "Test Engineer",
    "Test ortamı": "Test environment",
    "Test ortamı adresleri için sorumlu kaydı": "Owner record for the test environment addresses",
    "Test ortamı aralıkları": "Test environment ranges",
    "Test ortamı sahipleri": "Test environment owners",
    "Test ortamında hafta boyu hata döndü": "Returned errors all week in the test environment",
    "Test ortamında {N} adres hata alıyor": _p("{N} address is failing in the test environment", "{N} addresses are failing in the test environment"),
    "Test ortamındaki adreslerde sunucu ve istemci hataları var; üretimle ayrı değerlendirilir.": "The test environment addresses show server and client errors; assessed separately from production.",
    "Toplam {N} bağlantı denemesi, {N} ağ": "{N1} connection attempts in total across {N2} networks",
    "Tüm bilgisayarlar, ortanca": "All computers, median",
    "Tüm kullanıcılar": "All users",
    "Tür": "Type",
    "Ulaştığı ağlar birimiyle aynı": "The networks reached match those of their unit",
    "Ulaştığı ağların hepsi grubunun da gittiği yerler": "All the networks reached are places their group also goes to",
    "Ulaştığı {N} ödeme ve kart ağına birimindeki {N} kişiden hiçbiri gitmiyor": "None of the {N2} people in their unit go to the {N1} payment and card networks they reached",
    "Ulaşılan ağlar": "Networks reached",
    "Ulaşılan yeni ağ": "New networks reached",
    "Ulaşıldı": "Reached",
    "Uluslararası Operasyonlar BT": "International Operations IT",
    "Uyarı": "Alerts",
    "Uygulama Sunucuları": "Application Servers",
    "Uygulama geçidi": "Application gateway",
    "Uyum Uzmanı": "Compliance Specialist",
    "Uyum yöneticisi": "Compliance manager",
    "Uyum, sürekli engellenen istek": "Compliance, persistently blocked requests",
    "Uzak sistem keşfi": "Remote system discovery",
    "Uç nokta": "Endpoint",
    "Uç nokta koruması": "Endpoint protection",
    "Uç nokta koruması dosyayı engelledi": "Endpoint protection blocked the file",
    "Uç nokta koruması sahibi": "Endpoint protection owner",
    "Uç nokta olayı": "Endpoint event",
    "Uç noktada saldırı aracı": "Attack tool on endpoint",
    "VPN günlükleri": "VPN logs",
    "VPN istemcisinin zimmet kaydı ve cihaz sertifikası": "Assignment record and device certificate of the VPN client",
    "VPN oturumlarının açıldığı cihaz ve sertifika": "Device and certificate the VPN sessions were opened from",
    "VPN ve oturum davranışı olağan": "VPN and session behavior are normal",
    "VPN İstemcileri": "VPN Clients",
    "Varlık": "Entity",
    "Veritabanı Sunucuları": "Database Servers",
    "Yazılım Geliştirme Uzmanı": "Software Development Specialist",
    "Yeni ağların envanter kaydı": "Inventory record of the new networks",
    "Yeni istasyonların kullanım amacı": "Purpose of the new stations",
    "Yeni iç ağ": "New internal network",
    "Yeni iç ağa gidiş": "New internal network access",
    "Yeni iç ağa ulaşıldı": "New internal network reached",
    "Yeni iç ağlara ilk istek": "First requests to new internal networks",
    "Yetki yükseltme": "Privilege escalation",
    "Yoklama hatası": "Polling error",
    "Yoğun gün": "Peak day",
    "Yoğunluk düştü": "Activity dropped",
    "Yönetici hesabı taban haftada {N} istasyondan doğruladı, {D}'da {N} istasyondan": "The admin account authenticated from {N1} stations in the baseline week and from {N2} on {D}",
    "Yönetici hesabı taban haftada {N} istasyondan doğruladı, {D}'da {N} istasyondan doğruladı; aynı gün {N} yeni iç ağa ulaştı.": "The admin account authenticated from {N1} stations in the baseline week and from {N2} on {D}; the same day it reached {N3} new internal networks.",
    "Yönetici hesabı {N} yerine {N} istasyondan doğruladı, aynı gün {N} yeni iç ağa ulaştı": "The admin account authenticated from {N2} stations instead of {N1}; the same day it reached {N3} new internal networks",
    "Yönetici yetkili hesap": "Admin-privileged account",
    "Yönetici yetkisi": "Admin privileges",
    "Yönetici yetkisi hareketi": "Admin privilege activity",
    "Yönetici yetkisi kullanan hesap; {D}'da {N} istasyondan doğruladı (taban {N})": "Account using admin privileges; authenticated from {N1} stations on {D} (baseline {N2})",
    "Yönetim Ağı": "Management Network",
    "Yönetim ağı": "Management network",
    "Yönetim ağına deneme": "Attempt on the management network",
    "Yönetim ağına istek": "Request to the management network",
    "Yüksek": "High",
    "Zafiyet taraması": "Vulnerability scanning",
    "adres bloğunun sahibi ve test kaydı": "address block owner and test record",
    "aynı birimde {N} kişi, aynı gün": "{N} people in the same unit, same day",
    "ayrılıştan sonra hesap etkin": "account active after departure",
    "baskın kod": "dominant code",
    "benzerlerinde olağan": "typical for peers",
    "bilgisayar, kişi çözümlenemedi": "computer, person could not be resolved",
    "bilinen saldırı aracı adı": "name of a known attack tool",
    "birden çok gün": "multiple days",
    "birden çok imza sınıfı": "multiple signature classes",
    "birden çok kişide aynı desen": "same pattern across several people",
    "bu bloklar için yetkili test ya da tarama kaydı": "authorized test or scan record for these blocks",
    "bu dönemde uç nokta kaydı yok": "no endpoint records in this period",
    "bu servisler için sağlık kontrolü alarmı": "health check alarm for these services",
    "daha önce gidilmemiş ödeme ağları": "payment networks never accessed before",
    "dakika aralık": "minute interval",
    "dakikada bir kök yol, sürekli hata": "root path every minute, constant errors",
    "denetimli sızma testi olabilir": "could be an authorized penetration test",
    "dizin hesabı": "directory account",
    "dizüstü": "laptop",
    "doğrulayan kaynak": "confirming sources",
    "dönemde ilk kez gidilen ağlar": "networks accessed for the first time in the period",
    "dış adres": "external addresses",
    "dış adres bloğu, imzalı istek": "external address block, signature-matching requests",
    "engellenen ağ": "blocked networks",
    "engellenen ağların kaldırılmış aralıklar olup olmadığı": "whether the blocked networks are decommissioned ranges",
    "farklı port": "distinct ports",
    "gece saatlerinde {N} gece": "night-time activity on {N} nights",
    "geçen istek": "allowed requests",
    "grupta olağan": "group norm",
    "grupta olağanın {N} katı": "{N} times the group norm",
    "grupta olağanın üzerinde": "above the group norm",
    "gün": "days",
    "hafta boyu sunucu hatası, alarm üretilmemiş": "server errors all week, no alarm raised",
    "haftanın her dakikası": "every minute of the week",
    "hangi uygulama bu adresleri çağırıyor": "which application is calling these addresses",
    "hata kodu {N}xx, servis tarafı": "error code {N}xx, service side",
    "hedefler kaldırılmış aralıklar olabilir": "the targets could be decommissioned ranges",
    "hesabın {K} ve {K} için erişim talebi": "the account's access request for {K1} and {K2}",
    "hesap yetkisi kalmış olabilir": "the account may have retained its permissions",
    "hiçbir istek geçmedi": "no request got through",
    "hâlâ trafik alan servisler ve çağıran uygulamalar": "services still receiving traffic and the applications calling them",
    "hâlâ çağrılmaya devam ediyor": "still being called",
    "imzalı istek": "signature-matching requests",
    "istasyon, taban {N}": "stations, baseline {N}",
    "kaldırılmış bir kaynağa ayarlanmış istemci olabilir": "could be a client configured for a decommissioned resource",
    "kaldırılmış test aralıkları": "decommissioned test ranges",
    "kayıt yok": "no record",
    "kayıtlarda tanımlı değil": "not defined in the records",
    "kayıtlı kullanıcı: {K}": "registered user: {K}",
    "kişi çözümlenemedi": "person could not be resolved",
    "kullanıcı güvenlik uzmanı, test amaçlı olabilir": "the user is a security specialist; could be for testing",
    "kullanıcının bu ağa erişmesi gereken görev": "task requiring the user to access this network",
    "kısa sürede çok hedef": "many targets in a short time",
    "kısa sürede çok sayıda iç ağ": "many internal networks in a short time",
    "lokasyon, istemci sürümü, VPN profili": "location, client version, VPN profile",
    "nüfusun {P}'ünde görülen bir davranış": "a behavior seen in {P} of the population",
    "planlı bakım olabilir": "could be planned maintenance",
    "port çeşitliliği yüksek": "high port diversity",
    "sunucu hatası isteği": "server error requests",
    "taban haftaya göre {N} kat istasyon": "{N} times as many stations as the baseline week",
    "taleplerim ve apm servisleri için envanterde sorumlu kaydı": "owner record in the inventory for the taleplerim and apm services",
    "test amaçlı çağrı olabilir": "could be a test call",
    "test ortamları kaldırılmış olabilir": "the test environments may have been decommissioned",
    "test ortamı": "test environment",
    "test ortamı erişimi, istemci sürümü": "test environment access, client version",
    "ulaşılan yeni ağ": "new networks reached",
    "ulaşılan ödeme ağı": "payment networks reached",
    "ulaşıldı": "reached",
    "uygulama geçidi kaydı": "application gateway log",
    "uç nokta aksiyonu": "endpoint action",
    "uç nokta kaydı": "endpoint record",
    "web uygulamalarına saldırı imzası gönderiyor": "sending attack signatures to web applications",
    "yapılandırma hatası olabilir": "could be a configuration error",
    "yeni görev ya da proje olabilir": "could be a new assignment or project",
    "yeni iç ağ": "new internal network",
    "yeni iç ağlara ulaşım": "access to new internal networks",
    "yetkili zafiyet taraması olabilir": "could be an authorized vulnerability scan",
    "yönetici yetkisi": "admin privileges",
    "yönetim ağına erişimi gerektiren denetim görevi": "audit task requiring access to the management network",
    "yük dengeleyici sağlık kontrolü olabilir": "could be a load balancer health check",
    "{D}": "{D}",
    "{D} - {D}": "{D1} - {D2}",
    "{D} için değişiklik ve bakım talepleri": "change and maintenance requests for {D}",
    "{D} için planlı bakım ya da değişiklik talebi": "planned maintenance or change request for {D}",
    "{D} {T}": "{D} {T}",
    "{D}'da bilinen saldırı aracı arşivi tespit edildi ve engellendi": "A known attack tool archive was detected and blocked on {D}",
    "{D}'ta istasyon sayısı taban düzeyine döndü": "On {D} the station count returned to baseline",
    "{D}'ta yönetim ağına istek gönderdi; engellendi": "On {D} sent a request to the management network; it was blocked",
    "{D}'ta {N} yeni iç ağa istek gönderdi; {N}'ine ulaştı": "On {D} sent requests to {N1} new internal networks; reached {N2}",
    "{D}, {D}": "{D1}, {D2}",
    "{D}, {T}": "{D}, {T}",
    "{K}": "{K}",
    "{K} adresi atandı; iç kullanıcı ağı ve uygulama sunucularına {N} bağlantı": "{K} was assigned; {N} connections to the internal user network and application servers",
    "{K} adresinden; ilk {N} dakikada {N} ağ": "From {K}; {N2} networks in the first {N1} minutes",
    "{K} adresini alan istemci": "The client that received the address {K}",
    "{K} engellendi": "{K} blocked",
    "{K} engellendi, ilk kez": "{K} blocked, first time",
    "{K} ilk imza": "{K} first signature",
    "{K} için açık erişim talebi": "Open access request for {K}",
    "{K} için envanter ve topoloji karşılığı": "Inventory and topology match for {K}",
    "{K} için erişim talebi ya da görev kaydı": "Access request or assignment record for {K}",
    "{K} için kullanıcının erişim beklentisi": "The user's access expectation for {K}",
    "{K} kaynak ağ": "{K} source network",
    "{K} ulaşıldı": "{K} reached",
    "{K} ulaşıldı; {N} ağ engellendi": "{K} reached; {N} networks blocked",
    "{K} uç nokta olayı": "{K} endpoint event",
    "{K} ve {K} için istek gönderildi, engellendi": "Requests to {K1} and {K2} were sent and blocked",
    "{K} ve {K}, izinli": "{K1} and {K2}, allowed",
    "{K} zimmet kaydı": "{K} assignment record",
    "{K} üzerinde uzak masaüstü oturumu; hesap için ilk kez görülen bilgisayar": "Remote desktop session on {K}; a computer seen for the first time for this account",
    "{K}, Altyapı ve Sistem Yönetimi": "{K}, Infrastructure and Systems Management",
    "{K}, Bilgi Güvenliği": "{K}, Information Security",
    "{K}, Kredi Operasyonları": "{K}, Credit Operations",
    "{K}, Mali İşler": "{K}, Finance",
    "{K}, Uyum": "{K}, Compliance",
    "{K}, engellendi": "{K}, blocked",
    "{K}, uç nokta koruması engelledi": "{K}, blocked by endpoint protection",
    "{K}, uç noktada saldırı aracı": "{K}, attack tool on endpoint",
    "{K}, {K} ve {K} ağlarına {N} bağlantı, hepsi izinli": "{N} connections to the {K1}, {K2} and {K3} networks, all allowed",
    "{K}, {K}, {K}": "{K1}, {K2}, {K3}",
    "{K}, {K}, {K}, {K}": "{K1}, {K2}, {K3}, {K4}",
    "{K}, Ödeme Operasyonları": "{K}, Payment Operations",
    "{K}, İç Denetim": "{K}, Internal Audit",
    "{N} / {N}": "{N1} / {N2}",
    "{N} / {N} kişi, engellenen iç ağ istekleri": "{N1} / {N2} people, blocked internal network requests",
    "{N} adres": _p("{N} address", "{N} addresses"),
    "{N} adres artık yok": _p("{N} address no longer exists", "{N} addresses no longer exist"),
    "{N} adres {N} döndürüyor, çağrılar sürüyor": "{N1} addresses return {N2}; calls continue",
    "{N} adres {N} gündür aynı hedeflere imzalı istek gönderiyor": "{N1} addresses have been sending signature-matching requests to the same targets for {N2} days",
    "{N} adres {N} gündür imzalı istek gönderiyor": "{N1} addresses have been sending signature-matching requests for {N2} days",
    "{N} adres {N} gündür web uygulamalarına saldırı imzası gönderiyor": "{N1} addresses have been sending attack signatures to web applications for {N2} days",
    "{N} adres, {N} imzalı istek": "{N1} addresses, {N2} signature-matching requests",
    "{N} ayrı kaynak doğruladı": "{N} separate sources confirmed",
    "{N} ayrı kaynakta iz": "traces in {N} separate sources",
    "{N} ağ": _p("{N} network", "{N} networks"),
    "{N} ağ, {N} cihaz": "{N1} networks, {N2} devices",
    "{N} bilgisayar": _p("{N} computer", "{N} computers"),
    "{N} bilgisayarın ortak noktası": "What the {N} computers have in common",
    "{N} bilgisayarın ortak yapılandırması": "Shared configuration of the {N} computers",
    "{N} bilgisayarın {N}'inde": "In {N2} of {N1} computers",
    "{N} cihaz": _p("{N} device", "{N} devices"),
    "{N} dış adres bloğu": _p("{N} external address block", "{N} external address blocks"),
    "{N} dış adres, {N} imzalı istek; {P}'i uygulama geçidinde engellendi": "{N1} external addresses, {N2} signature-matching requests; {P} blocked at the application gateway",
    "{N} dış bloğun {N}'inde": "In {N2} of {N1} external blocks",
    "{N} dış bloğun {N}'ünde": "In {N2} of {N1} external blocks",
    "{N} engellenen istek": _p("{N} blocked request", "{N} blocked requests"),
    "{N} engellenen istek, {D}'ın {P} kadarı": "{N1} blocked requests, about {P} of the {D} volume",
    "{N} engellenen istek, {N} kişi için en yoğun gün": "{N1} blocked requests, peak day for {N2} people",
    "{N} farklı port": "{N} different ports",
    "{N} gece": _p("{N} night", "{N} nights"),
    "{N} gece VPN oturumu, {T} ile {T} arası": "VPN sessions on {N} nights, between {T1} and {T2}",
    "{N} gece art arda VPN oturumu ({T} ile {T} arası)": "VPN sessions on {N} consecutive nights (between {T1} and {T2})",
    "{N} gün süreklilik": "{N} days of continuity",
    "{N} gündür aynı ağa istek, günde ortalama {N} ret": "Requests to the same network for {N1} days, averaging {N2} denials a day",
    "{N} gündür aynı iç ağa engelleniyor, günde ortalama {N} reddedilen istek": "Blocked from the same internal network for {N1} days, averaging {N2} denied requests a day",
    "{N} gündür aynı iç ağa istek gönderiyor; her seferinde engellendi": "Has been sending requests to the same internal network for {N} days; blocked every time",
    "{N} gündür aynı iç ağa istek, günde ortalama {N} ret": "Requests to the same internal network for {N1} days, averaging {N2} denials a day",
    "{N} hesap": _p("{N} account", "{N} accounts"),
    "{N} imzalı istek, {N} adres": "{N1} signature-matching requests, {N2} addresses",
    "{N} istasyon": _p("{N} station", "{N} stations"),
    "{N} istasyondan doğrulama, günde {N} ile {N} yetkili oturum": "Authentication from {N1} stations, {N2} to {N3} privileged sessions a day",
    "{N} istek": _p("{N} request", "{N} requests"),
    "{N} iç ağ engellendi": "{N} internal networks blocked",
    "{N} iç ağ engellendi, ilk kez": "{N} internal networks blocked, first time",
    "{N} iç ağa istek gönderdi, hiçbiri geçmedi (grupta olağan {N})": "Sent requests to {N1} internal networks, none got through (group norm {N2})",
    "{N} iç ağa istek gönderdi, hiçbiri geçmedi; grupta olağan {N}": "Sent requests to {N1} internal networks, none got through; group norm {N2}",
    "{N} kaynak doğruladı": _p("{N} source confirmed", "{N} sources confirmed"),
    "{N} kaynakta iz: VPN, etki alanı, güvenlik duvarı": "Traces in {N} sources: VPN, domain controller, firewall",
    "{N} kişi": _p("{N} person", "{N} people"),
    "{N} kişi, {N} bilgisayar": "{N1} person, {N2} computer",
    "{N} kişiden toplam {N} engellenen istek": "{N1} people sent {N2} blocked requests in total",
    "{N} kişilik gruptan {N}'si {N} ile {N} arasında iç ağa istek gönderdi, hiçbiri geçmedi": "{N2} of a {N1}-person group sent requests to {N3} to {N4} internal networks, none got through",
    "{N} kişilik gruptan {N}'u yüzlerce iç ağa istek gönderdi, hiçbiri geçmedi": "{N2} of a {N1}-person group sent requests to hundreds of internal networks, none got through",
    "{N} kişinin hiçbiri olağan dışı sayıda ağa istek göndermedi": "None of the {N} people sent requests to an unusual number of networks",
    "{N} kişinin tamamından {N} engellenen istek": "{N2} blocked requests from all {N1} people",
    "{N} kişinin {N}'sinde": "In {N2} of {N1} people",
    "{N} kişinin {N}'unda": "In {N2} of {N1} people",
    "{N} kullanıcının {N}'inde": "In {N2} of {N1} users",
    "{N} kullanıcının {N}'sinde": "In {N2} of {N1} users",
    "{N} oturum": _p("{N} session", "{N} sessions"),
    "{N} saat": _p("{N} hour", "{N} hours"),
    "{N} saatte taranan ağ": "networks scanned in {N} hours",
    "{N} saatte {N} iç ağ ve {N} port; benzer bilgisayarlarda olağan {N} ağ": "{N2} internal networks and {N3} ports in {N1} hours; typical for similar computers: {N4} networks",
    "{N} saatte {N} iç ağa, {N} farklı porta istek ({P} reddedildi)": "Requests to {N2} internal networks and {N3} distinct ports in {N1} hours ({P} denied)",
    "{N} servis": _p("{N} service", "{N} services"),
    "{N} servis için kök yola yoklama, sürekli {N}xx": "Polling the root path of {N1} services, constant {N2}xx",
    "{N} servis için sağlık kontrolü adresi": "Health check address for {N} services",
    "{N} servis için sorumlu ekip": "Owner team for {N} services",
    "{N} servis için sorumlu ekip; {N} servisin envanterde sorumlusu yok": "Owner team for {N1} services; {N2} of the services have no owner in the inventory",
    "{N} servis için tanımlı sağlık alarmı olup olmadığı": "Whether a health alarm is defined for the {N} services",
    "{N} servis için tanımlı sağlık kontrolü adresi": "Defined health check address for the {N} services",
    "{N} servisin {N}'sinde": "In {N2} of {N1} services",
    "{N} servisin {N}'sında": "In {N2} of {N1} services",
    "{N} servisin {N}'ünde": "In {N2} of {N1} services",
    "{N} serviste kesintisiz {N}xx; alarm yok": "{N1} services returning {N2}xx without a break; no alarm",
    "{N} sunucu": _p("{N} server", "{N} servers"),
    "{N} test adresinin {N}'ünde": "In {N2} of {N1} test addresses",
    "{N} ve {N} yanıtları": "{N1} and {N2} responses",
    "{N} yanıtları": "{N} responses",
    "{N} yeni istasyondan ilk doğrulama": "First authentication from {N} new stations",
    "{N} yeni iç ağ": _p("{N} new internal network", "{N} new internal networks"),
    "{N} yeni iç ağ, istek engellendi": _p("{N} new internal network, request blocked", "{N} new internal networks, requests blocked"),
    "{N} yeni iç ağ, {N}'ine ulaştı, {N}'sine istek engellendi": "{N1} new internal networks: {N2} reached, requests to {N3} blocked",
    "{N} yeni iç ağ: {N} ulaşıldı, {N} engellendi": "{N1} new internal networks: {N2} reached, {N3} blocked",
    "{N} yeni iç ağa istek gönderdi, engellendi": _p("Sent a request to {N} new internal network, blocked", "Sent requests to {N} new internal networks, blocked"),
    "{N} yeni iç ağa ulaştı: ödeme ve kart sistemleri": "Reached {N} new internal networks: payment and card systems",
    "{N} yeni iç ağa ulaşım": "Access to {N} new internal networks",
    "{N} yoklama yanlış adrese gidiyor": "{N} polls are going to the wrong address",
    "{N} yönetici hesabın {N}'inde": "In {N2} of {N1} admin accounts",
    "{N} yönetim ağına istek gönderdi, engellendi": "Sent requests to {N} management networks, blocked",
    "{N} üretim servisi": "{N} production services",
    "{N} üretim servisi hafta boyu {N}xx döndürüyor, hiçbirinde alarm yok": "{N1} production services have been returning {N2}xx all week, none has an alarm",
    "{N} üretim servisi {N} günün {N}'sinde sunucu hatası döndürüyor: üçü haftanın her dakikası ({N} istek), diğerleri en az {N} istek boyunca. Bu süre boyunca hiçbir alarm oluşmamış.": "{N1} production services return server errors on {N3} of {N2} days: three of them every minute of the week ({N4} requests), the others for at least {N5} requests. No alarm was raised during this time.",
    "{N}, VPN günlükleri": "{N}, VPN logs",
    "{N}, VPN, etki alanı, güvenlik duvarı": "{N}, VPN, domain controller, firewall",
    "{N}, etki alanı, güvenlik duvarı": "{N}, domain controller, firewall",
    "{N}, iç güvenlik duvarı": "{N}, internal firewall",
    "{N}, uygulama geçidi": "{N}, application gateway",
    "{N}, uç nokta koruması": "{N}, endpoint protection",
    "{P}": "{P}",
    "Çar": "Wed", "Pzt": "Mon", "Sal": "Tue", "Per": "Thu", "Cum": "Fri", "Cmt": "Sat", "Paz": "Sun",
    "Çağıran uygulama": "Calling application",
    "Çekirdek Bankacılık, uygulama": "Core Banking, application",
    "Çoklu kaynak": "Multi-source",
    "Ödeme Operasyonları": "Payment Operations",
    "Ödeme Operasyonları, işten ayrıldı, hesap etkin": "Payment Operations, departed, account active",
    "Ödeme Platformu Ekibi": "Payment Platform Team",
    "Ödeme Sistemleri, uygulama": "Payment Systems, application",
    "Ödeme Sistemleri, veritabanı": "Payment Systems, database",
    "Ödeme ağları için erişim talebi ve onayı": "Access request and approval for the payment networks",
    "Ödeme ağlarına ilk ulaşım": "First access to the payment networks",
    "Ödeme ağlarındaki erişimin yetkisi": "Authorization for the access in the payment networks",
    "Ödeme ağına ulaşıldı": "Payment network reached",
    "Ödeme sistemleri sahibi": "Payment systems owner",
    "Ödeme ve Kart Sistemleri": "Payment and Card Systems",
    "Ödeme ve kart ağlarına {N} bağlantı": "{N} connections to the payment and card networks",
    "Ölçü": "Metric",
    "Ölü adres": "Dead address",
    "Ölü adres çağrısı": "Dead address call",
    "Öncelik": "Priority",
    "Üretim ortamı": "Production environment",
    "Üretim uygulama sunucuları": "Production application servers",
    "Üretim uygulama sunucuları {N}": "Production application servers {N}",
    "Ürün Analisti": "Product Analyst",
    "Üç servis için izleme kök yola istek gönderiyor ve sürekli hata alıyor; izleme ayarı yanlış adrese bakıyor olabilir.": "Monitoring sends requests to the root path for three services and constantly gets errors; the monitoring setting may be pointing at the wrong address.",
    "Üçüncü Taraflar": "Third Parties",
    "Üçüncü taraf güvenlik duvarı (Palo Alto)": "Third-party firewall (Palo Alto)",
    "çözümlenemedi": "could not be resolved",
    "üretilen alarm": "alarms raised",
    "üretimden ayrı değerlendirilir": "assessed separately from production",
    "İK durumu": "HR status",
    "İK kaydı gecikmeli girilmiş olabilir": "the HR record may have been entered late",
    "İK kaydı ve dizin hesabı": "HR record and directory account",
    "İK ve kimlik yönetimi": "HR and identity management",
    "İK ve kimlik yönetimi sürecinde bu hesap için iş kaydı": "Ticket for this account in the HR and identity management process",
    "İki uygulama adresi {N} döndürüyor ama istekler kesilmemiş; çağıran uygulama ayarı güncellenmemiş olabilir.": "Two application addresses return {N} but requests have not stopped; the calling application's setting may not have been updated.",
    "İlk engellenen istekler": "First blocked requests",
    "İlk erişim": "Initial access",
    "İlk gece VPN oturumu": "First night-time VPN session",
    "İlk görülme": "First seen",
    "İlk imzalı istek": "First signature-matching request",
    "İmza sınıfı": "Signature class",
    "İmzalı istek": "Signature-matching requests",
    "İndirilenler klasöründe saldırı aracı arşivi tespit edildi: {K}": "Attack tool archive detected in the Downloads folder: {K}",
    "İnternet": "Internet",
    "İnternet DMZ": "Internet DMZ",
    "İnternet güvenlik duvarı (Palo Alto)": "Internet firewall (Palo Alto)",
    "İnternete açık uygulamayı sömürme": "Exploit public-facing application",
    "İnternetten bir adres bloğu {N} gündür imzalı istek gönderiyor; istekler uygulama geçidinde engellendi.": "An address block on the internet has been sending signature-matching requests for {N} days; the requests were blocked at the application gateway.",
    "İnternetten iki adres bloğu, birden çok gündür web uygulamalarına saldırı imzalı istek gönderiyor; isteklerin {P}'i engellendi.": "Two address blocks on the internet have been sending signature-matching requests to web applications for several days; {P} of the requests were blocked.",
    "İstasyon": "Station",
    "İstasyon sayısı taban düzeyine döndü": "Station count returned to baseline",
    "İstasyonlar": "Stations",
    "İstek": "Requests",
    "İstekler sürüyor": "Requests continue",
    "İstekleri gönderen program": "Program sending the requests",
    "İstemci sürümü, VPN profili ve lokasyon bilgisi": "Client version, VPN profile and location",
    "İzleme adreslerinin düzeltilmesi": "Fixing the monitoring addresses",
    "İzleme ekibi": "Monitoring team",
    "İzleme kapsamı": "Monitoring coverage",
    "İzleme tanımlarının gözden geçirilmesi": "Reviewing the monitoring definitions",
    "İzleme tanımı": "Monitoring definition",
    "İç Denetim": "Internal Audit",
    "İç Denetim, yeni iç ağa gidiş": "Internal Audit, access to a new internal network",
    "İç Denetçi": "Internal Auditor",
    "İç denetim çalışması için yönetim ağı erişim gerekçesi": "Justification for management network access for the internal audit work",
    "İç güvenlik duvarı": "Internal firewall",
    "İç güvenlik duvarı (Check Point)": "Internal firewall (Check Point)",
    "İç keşif": "Discovery",
    "İşten ayrıldı, {D}": "Left the company, {D}",
    "İşten ayrıldı, {D}; hesap etkin ve dönemde {N} oturum açmış": "Left the company on {D}; account active and {N} sessions opened in the period",
    "İşten ayrıldıktan sonra hesap etkin; gece VPN ile ödeme ağlarına ulaşıldı": "Account active after departure; payment networks reached over VPN at night",
    # ---- ASCII yazilan Turkce metinler
    "Aktif tarama": "Active scanning",
    "Benzer bilgisayarlarda ortanca": "Median for similar computers",
    "Benzerlerinden giden": "Peers going there",
    "Bu bilgisayar": "This computer",
    "Check Point": "Check Point",
    "Citrix ADC": "Citrix ADC",
    "Dijital Kanallar": "Digital Channels",
    "Ekip Lideri": "Team Lead",
    "Engellenen istek": "Blocked requests",
    "Engellenen istek, toplam": "Blocked requests, total",
    "Engellenen pay": "Blocked share",
    "Felaket Merkezi": "Disaster Recovery Site",
    "Gece saatinde oturum": "Night-time session",
    "Gece saatlerinde": "At night",
    "Hedef uygulamalar": "Target applications",
    "Hedeflerin durumu": "Status of the targets",
    "Intranet DMZ": "Intranet DMZ",
    "Kart Sistemleri Ekibi": "Card Systems Team",
    "Kart Sistemleri, uygulama": "Card Systems, application",
    "Kurumsal Uygulamalar": "Corporate Applications",
    "Meridyen Finans": "Meridyen Finance",
    "Microsoft Windows": "Microsoft Windows",
    "Palo Alto GlobalProtect": "Palo Alto GlobalProtect",
    "Reddedilen pay": "Denied share",
    "SSL VPN (Palo Alto)": "SSL VPN (Palo Alto)",
    "Servis sahibi": "Service owner",
    "Servis sahibi ekiplerin bilgilendirilmesi": "Notifying the service owner teams",
    "Sistem ekibi": "Systems team",
    "Son gece oturumu": "Last night-time session",
    "Sorumlu ekipler": "Owner teams",
    "Sunucu envanteri": "Server inventory",
    "Tarama sona erdi": "Scan ended",
    "Tek kaynak": "Single source",
    "Trend Micro Apex Central": "Trend Micro Apex Central",
    "Uygulama adresi": "Application address",
    "Uygulama sahipleri": "Application owners",
    "Uzak servisler": "Remote services",
    "VPN oturumundan": "From the VPN session",
    "Yanal hareket": "Lateral movement",
    "Yetkili oturum": "Privileged sessions",
    "alarm yok": "no alarm",
    "engellenen istek": "blocked requests",
    "gece oturumu": "night sessions",
    "izleme hizmeti olabilir": "could be a monitoring service",
    "kaynak adres": "source address",
    "reddedilen istek": "denied requests",
    "tekrarlayan ret": "repeated denials",
    "yeni sunucu kurulumu olabilir": "could be a new server setup",
    "yetkili oturum": "privileged sessions",
    "Durum": "Status",
    "Kaynak": "Source",
    "Ad": "Name", "Adet": "Count", "Adres": "Address", "Adresler": "Addresses", "Aksiyon": "Action", "Alan": "Field",
    "Alarm": "Alarm", "Bilgisayar": "Computer", "Birim": "Unit", "Blok": "Block", "Bloklar": "Blocks", "Bulgu": "Finding",
    "Dosya": "File", "Ekip": "Team", "Engellendi": "Blocked", "Etkin": "Active", "Kod": "Code", "Konum": "Location",
    "Orta": "Medium", "Ortam": "Environment", "Pay": "Share", "Reddedilen": "Denied", "Servisler": "Services",
    "Sorumlu": "Owner", "Sunucu": "Server", "Taban": "Baseline", "Test": "Test", "Unvan": "Title", "Uyum": "Compliance", "Yol": "Path",
    "engellendi": "blocked", "engellenen": "blocked", "hata": "errors", "istek": "requests", "tespit": "detection",
    "yoklama": "polls", "servis": "services", "kaynak": "source",
}
